version: '3.4'

services:
  sfdb:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      SA_PASSWORD: MasterOfPuppets2020
      ACCEPT_EULA: Y
    ports: 
      - "1433:1433"
  api:
    image: ${DOCKER_REGISTRY-}sfwebapi
    build:
      context: .
      dockerfile: SF.WebAPI/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:443;http://+:80
    ports: 
      - "3224:443"
      - "3225:80"